version: "3.3"

services:
  gusmelford.db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - gusmelforddb:/var/lib/postgresql/data
      - datalake:/datalake

  gusmelfordbot.core:
    image: $DOCKER_REPO/$CONTAINER_NAME:$DOCKER_CONTAINER_TAG
    restart: always
    depends_on:
      - gusmelford.db
    ports:
      - $PORT:80
    environment:
      - AppSettings:Name=GusMelfordBot
      - AppSettings:Version=1.6.5
      - AppSettings:TelegramBotSettings:Token=$GUSMELFORDBOT_TELEGRAM_TOKEN
      - AppSettings:DatabaseSettings:Host=$GUSMELFORDBOT_HOST
      - AppSettings:DatabaseSettings:Port=5432
      - AppSettings:DatabaseSettings:Database=dev.gusmelfordbot.db
      - AppSettings:DatabaseSettings:Username=$POSTGRES_USER
      - AppSettings:DatabaseSettings:Password=$POSTGRES_PASSWORD
      - AppSettings:FtpServerSettings:FtpUrl=$FTP_URL
      - AppSettings:FtpServerSettings:UserName=$FTP_USER
      - AppSettings:FtpServerSettings:Password=$FTP_PASSWORD
      - Serilog:WriteTo:0:Name=GrayLog
      - Serilog:WriteTo:0:Args:HostnameOrAddress=$GUSMELFORDLOG_HOST
      - Serilog:WriteTo:0:Args:Port=12201
      - Serilog:WriteTo:0:Args:TransportType=Udp
      - Serilog:Properties:Application=GusMelfordBot

volumes:
  gusmelforddb:
  datalake: