version: "3.3"

services:
  gusmelford.db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - gusmelforddb:/var/lib/postgresql/data

  gusmelfordbot.core:
    image: $DOCKER_REPO/$CONTAINER_NAME:$DOCKER_CONTAINER_TAG
    restart: always
    depends_on:
      - gusmelford.db
    ports:
      - $PORT:80
    environment:
      - CommonSettings__Name=GusMelfordBot
      - CommonSettings__Version=1.6.1
      - CommonSettings__TelegramBotSettings__Token=$GUSMELFORDBOT_TELEGRAM_TOKEN
      - CommonSettings__DatabaseSettings__Host=$GUSMELFORDBOT_HOST
      - CommonSettings__DatabaseSettings__Port=5432
      - CommonSettings__DatabaseSettings__Database=dev.gusmelfordbot.db
      - CommonSettings__DatabaseSettings__Username=$POSTGRES_USER
      - CommonSettings__DatabaseSettings__Password=$POSTGRES_PASSWORD
      - CommonSettings__GrayLogSettings__Host=$GUSMELFORDBOT_HOST
      - CommonSettings__GrayLogSettings__Port=12201
      - CommonSettings__GrayLogSettings__TransportType=Udp
      - CommonSettings__FtpServerSettings__FtpUrl=$FTP_URL
      - CommonSettings__FtpServerSettings__UserName=$FTP_USER
      - CommonSettings__FtpServerSettings__Password=$FTP_PASSWORD

  gusmelfordbot.core.addon:
    image: gsmelford/gusmelfordbot.core.addon:latest
    restart: always
    environment:
      - Token=$GUSMELFORDBOT_TELEGRAM_TOKEN
      - UpdateUrl=http://$GUSMELFORDBOT_HOST:$PORT/update

volumes:
  gusmelforddb: