version: "3.9"

services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  gusmelford.contentcollector:
    container_name: gusmelford.contentcollector
    image: $DOCKER_REPO/$CONTAINER_NAME_CONTENT:$DOCKER_CONTAINER_TAG
    restart: always
    ports:
      - 5670:80
    environment:
      - AppSettings:KafkaSettings:BootstrapServers=localhost
      - AppSettings:FtpSettings:FtpUrl=$FTP_URL
      - AppSettings:FtpSettings:UserName=$FTP_USER
      - AppSettings:FtpSettings:Password=$FTP_PASSWORD

  gusmelfordbot:
    container_name: gusmelfordbot
    image: $DOCKER_REPO/$CONTAINER_NAME:$DOCKER_CONTAINER_TAG
    restart: always
    depends_on:
      - db
    ports:
      - 5665:80
    environment:
      - AppSettings:TelegramBotSettings:Token=$GUSMELFORDBOT_TELEGRAM_TOKEN
      - AppSettings:KafkaSettings:BootstrapServers=localhost
      - AppSettings:DatabaseSettings:Host=db
      - AppSettings:DatabaseSettings:Port=5432
      - AppSettings:DatabaseSettings:Database=gusmelford.app
      - AppSettings:DatabaseSettings:Username=$POSTGRES_USER
      - AppSettings:DatabaseSettings:Password=$POSTGRES_PASSWORD
      - AppSettings:FtpSettings:FtpUrl=$FTP_URL
      - AppSettings:FtpSettings:Username=$FTP_USER
      - AppSettings:FtpSettings:Password=$FTP_PASSWORD