version: "3.3"

services:
  gusmelford.db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - gusmelforddb:/var/lib/postgresql/data

  gusmelford.contentcollector:
    image: $DOCKER_REPO/$CONTAINER_NAME_CONTENT:$DOCKER_CONTAINER_TAG
    restart: always
    ports:
      - 5668:80
    environment:
      - AppSettings:KafkaSettings:BootstrapServers=localhost
      - AppSettings:FtpSettings:FtpUrl=$FTP_URL
      - AppSettings:FtpSettings:Username=$FTP_USER
      - AppSettings:FtpSettings:Password=$FTP_PASSWORD

  gusmelfordbot.core:
    image: $DOCKER_REPO/$CONTAINER_NAME:$DOCKER_CONTAINER_TAG
    restart: always
    depends_on:
      - gusmelford.db
      - kafka
    ports:
      - $PORT:80
    environment:
      - AppSettings:TelegramBotSettings:Token=$GUSMELFORDBOT_TELEGRAM_TOKEN
      - AppSettings:KafkaSettings:BootstrapServers=localhost
      - AppSettings:DatabaseSettings:Host=$GUSMELFORDBOT_HOST
      - AppSettings:DatabaseSettings:Port=5432
      - AppSettings:DatabaseSettings:Database=gusmelford.app
      - AppSettings:DatabaseSettings:Username=$POSTGRES_USER
      - AppSettings:DatabaseSettings:Password=$POSTGRES_PASSWORD
      - AppSettings:FtpSettings:FtpUrl=$FTP_URL
      - AppSettings:FtpSettings:UserName=$FTP_USER
      - AppSettings:FtpSettings:Password=$FTP_PASSWORD

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.5
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: ubuntu/kafka:latest
    ports:
      - 9092:9092
      - 2181:2181
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    restart: always
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9001:8080
    environment:
      SERVER_SERVLET_CONTEXT_PATH: /kafka-ui
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

volumes:
  gusmelforddb:
  rabbitmqdata:
