version: "3.9"

services:
  gusmelford.contentcollector:
    container_name: gusmelford.contentcollector
    image: $DOCKER_REPO/$CONTAINER_NAME_CONTENT:$DOCKER_CONTAINER_TAG
    restart: always
    depends_on:
      - kafka
    ports:
      - 5670:80
    environment:
      - AppSettings:KafkaSettings:BootstrapServers=localhost
    volumes:
      - /home/melf/gusmelfordbot/contents:/app/contents

  gusmelfordbot:
    container_name: gusmelfordbot
    image: $DOCKER_REPO/$CONTAINER_NAME:$DOCKER_CONTAINER_TAG
    restart: always
    ports:
      - 5665:80
    environment:
      - AppSettings:AuthSettings:Key=$GUSMELFORD_BOT_KEY
      - AppSettings:TelegramBotSettings:Token=$GUSMELFORDBOT_TELEGRAM_TOKEN
      - AppSettings:KafkaSettings:BootstrapServers=localhost
      - AppSettings:DatabaseSettings:Host=localhost
      - AppSettings:DatabaseSettings:Port=5432
      - AppSettings:DatabaseSettings:Database=gusmelford.app
      - AppSettings:DatabaseSettings:Username=$POSTGRES_USER
      - AppSettings:DatabaseSettings:Password=$POSTGRES_PASSWORD
    volumes:
      - /home/melf/gusmelfordbot/contents:/app/contents
