version: "3.3"

services:
  gusmelford.db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - gusmelforddb:/var/lib/postgresql/data

  gusmelfordbot.core:
    image: gsmelford/gusmelfordbot.core:latest
    restart: always
    depends_on:
      - gusmelford.db
    ports:
      - "5665:80"
    environment:
      - CommonSettings__Name=GusMelfordBot
      - CommonSettings__Version=1.4.8
      - CommonSettings__PlayerVersion=4.4
      - CommonSettings__TelegramBotSettings__Token=$GUSMELFORDBOT_TELEGRAM_TOKEN
      - CommonSettings__DatabaseSettings__Host=$GUSMELFORDBOT_HOST
      - CommonSettings__DatabaseSettings__Port=5432
      - CommonSettings__DatabaseSettings__Database=dev.gusmelfordbot.db
      - CommonSettings__DatabaseSettings__Username=$POSTGRES_USER
      - CommonSettings__DatabaseSettings__Password=$POSTGRES_PASSWORD
      - CommonSettings__TikTokSettings__TikTokChatId=-1001529315725

volumes:
  gusmelforddb: